eproject/Models/Contest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eproject.Models
{
    public class Contest
    {
        public Contest()
        {
            //this.role = "ROLE_USER";
            // this.enabled = false;
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid id { get; set; }
        [StringLength(30, ErrorMessage = "The {0} must be at least 3 characters long.", MinimumLength = 3)]
        [Required(ErrorMessage = "Contest Name is Required")]
        [DisplayName("Contest Name")]
        [RegularExpression(@"^[a-zA-Z\s\d]+$", ErrorMessage = "Contest name must contain only letters and numbers")]
        public string name { get; set; }

        [Required(ErrorMessage = "Content is Required")]
        [StringLength(3000, ErrorMessage = "The {0} must be at least 3 characters long.", MinimumLength = 10)]
        [DataType(DataType.MultilineText)]
        [DisplayName("Content")]
        [AllowHtml]
        public string content { get; set; }

        [DataType(DataType.Date)]
        [DisplayName("Create Date")]
        public DateTime createAt { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Start Date is Required")]
        [DisplayName("Start Date")]
        public DateTime startDate { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "End Date is Required")]
        [DisplayName("End Date")]
        public DateTime endDate { get; set; }

        public Guid? winner { get; set; }

        public virtual ICollection<Recipe> recipes { get; set; }
    }
}

eproject/Controllers/ContestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eproject.Models;
using PagedList;



namespace eproject.Controllers
{
    public class ContestController : Controller
    {
        private context db = new context();
        // GET: Contest/Sorting/Searching/Paging 
        public ActionResult Index(string sortOrder, string currentFilter, string search, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.CreateDateSort = sortOrder == "datecreate" ? "createdate" : "datecreate";
            ViewBag.StartDateSort = sortOrder == "datestart" ? "stardate" : "datestart";
            ViewBag.EndDateSort = sortOrder == "dateend" ? "enddate" : "dateend";

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewBag.CurrentFilter = search;

            var contests = from c in db.contest
                           select c;

            if (!String.IsNullOrEmpty(search))
            {
                contests = contests.Where(c => c.name.Contains(search));
            }

            switch (sortOrder)
            {
                case "datecreate":
                    contests = contests.OrderBy(c => c.createAt);
                    break;
                case "name":
                    contests = contests.OrderBy(c => c.name);                  
                    break;
                case "":
                    contests = contests.OrderByDescending(c => c.name);
                    break; 
                case "datestart":
                    contests = contests.OrderBy(c => c.startDate);
                    break;
                case "stardate":
                    contests = contests.OrderByDescending(c => c.startDate);
                    break;
                case "dateend":
                    contests = contests.OrderBy(c => c.endDate);
                    break;
                case "enddate":
                    contests = contests.OrderByDescending(c => c.endDate);
                    break;
                default:
                    contests = contests.OrderByDescending(c => c.createAt);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(contests.ToPagedList(pageNumber, pageSize));
        }

        // GET: Contest/Details
        public ActionResult Readmore(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.contest.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // GET: ContestRecipe/Sorting/Searching/Paging 
        public ActionResult contestRecipe(string sortOrder, string currentFilter, string search, int? page, Guid? id, DateTime? endDate, Guid? winner)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.CreateDateSort = sortOrder == "datecreate" ? "createdate" : "datecreate";
            ViewBag.StartDateSort = sortOrder == "category" ? "recipecategory" : "category";
            ViewBag.endDate = endDate;
            if (winner != null)
            {
                var win = db.user.Find( db.recipe.Find(winner).manager).name ;
                ViewBag.winner = win;
            }

            ViewBag.w = winner;
            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewBag.CurrentFilter = search;

            var contestRecipes = from cr in db.recipe
                                 where cr.contest_id == id
                                 select cr;

            //Searching
            if (!String.IsNullOrEmpty(search))
            {
                contestRecipes = contestRecipes.Where(cr => cr.name.Contains(search));
            }

            //Sorting
            switch (sortOrder)
            {
                case "datecreate":
                    contestRecipes = contestRecipes.OrderBy(cr => cr.createAt);
                    break;
                case "name":
                    contestRecipes = contestRecipes.OrderBy(cr => cr.name);
                    break;
                case "":
                    contestRecipes = contestRecipes.OrderByDescending(cr => cr.name);
                    break;
                case "category":
                    contestRecipes = contestRecipes.OrderBy(cr => cr.category);
                    break;
                case "recipecategory":
                    contestRecipes = contestRecipes.OrderByDescending(cr => cr.category);
                    break;
                default:
                    contestRecipes = contestRecipes.OrderByDescending(cr => cr.createAt);
                    break;
            }

            //Paging
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(contestRecipes.ToPagedList(pageNumber, pageSize));
        }
    }
}

eproject/Controllers/RecipeExtendController.cs
using eproject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eproject.Helper;
using eproject.Security;

namespace eproject.Controllers
{
    public class RecipeExtendController : Controller
    {
        private context db = new context();
        // GET: RecipeExtend
        [HttpPost]

        public ActionResult rate(int ratting, string user, string recipe)
        {
            if (recipe == "" || user == "")
            {
                return Json(new { success = false, responseText = "you must log in before ratting!" }, JsonRequestBehavior.AllowGet);
            }
            Guid userId = Guid.Parse(user);
            Guid recipeId = Guid.Parse(recipe);
            var orate = db.ratting.Where(c => c.recipe_id == recipeId && c.own == userId);

            if (orate.Count() != 0)
            {
                return Json(new { success = false, responseText = "You already rate this recipe!" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Ratting nrate = new Ratting();
                nrate.rate = ratting;
                nrate.own = userId;
                nrate.recipe_id = recipeId;
                db.ratting.Add(nrate);
                db.SaveChanges();
                return Json(new { success = true, responseText = "You have rate this recipe " + ratting + " star!" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult recipeDetail(Guid id)
        {
            double rate = 0;
            int rateCount = 0;
            var recipe = db.recipe.Find(id);
            if (recipe.enabled == false)
            {
                return RedirectToAction("index", "home");
            }
            var type = recipe.type;
            if (type != "Free")
            {
                if (Session["userId"] != null)
                {
                    var u = db.user.Find(Session["userId"]);
                    if (u.expireDate < DateTime.Now && u.role != "ROLE_ADMIN")
                    {
                        return RedirectToAction("error", "home", new { msg = "Only vip user can see this recipe, go to profile to buy vip access!" });
                    }
                }
                else
                    return RedirectToAction("error", "home", new { msg = "Only vip user can see this recipe, go to profile to buy vip access!" });

            }
            ViewBag.manager = db.user.Find(recipe.manager).email;
            var srate = db.ratting.Where(m => m.recipe_id == recipe.id).Select(m => m.rate);
            if (srate.Count() > 0)
            {
                rate = srate.Average();
                rateCount = srate.Count();
            }
            //random 3 recipe with same category
            var relate = db.recipe.Where(m => m.category == recipe.category).OrderBy(x => Guid.NewGuid()).Take(3);

            var comment = db.feedBack.Where(m => m.recipe_id == recipe.id).ToArray();

            foreach (var item in comment)
            {
                item.ago = DateTimeConvert.TimeAgo(item.createAt);
                item.name = db.user.Find(item.own).name;

            }
            ViewBag.comment = comment;
            ViewBag.rateCount = rateCount;
            ViewBag.rate = rate;
            ViewBag.recipeId = id;
            ViewBag.relate = relate;
            //view count
            if (Request.Cookies["ViewedPage"] != null)
            {
                if (Request.Cookies["ViewedPage"][string.Format("pId_{0}", id)] == null)
                {
                    HttpCookie cookie = (HttpCookie)Request.Cookies["ViewedPage"];
                    cookie[string.Format("pId_{0}", id)] = "1";
                    cookie.Expires = DateTime.Now.AddDays(1);
                    Response.Cookies.Add(cookie);
                    recipe.viewCount = recipe.viewCount + 1;
                    db.SaveChanges();
                }
            }
            else
            {
                HttpCookie cookie = new HttpCookie("ViewedPage");
                cookie[string.Format("pId_{0}", id)] = "1";
                cookie.Expires = DateTime.Now.AddDays(1);
                Response.Cookies.Add(cookie);

                recipe.viewCount = recipe.viewCount + 1;
                db.SaveChanges();
            }
            return View(recipe);
        }
        [HttpPost]
        public ActionResult createComment(string content, string user, string recipe)
        {
            if (recipe == "" || user == "")
            {
                return Json(new { success = false, responseText = "you must log in before ratting!" }, JsonRequestBehavior.AllowGet);
            }
            if (content.Length < 20 || content.Length > 150)
            {
                return Json(new { success = false, responseText = "comment must at 20-150 character" }, JsonRequestBehavior.AllowGet);
            }
            Guid userId = Guid.Parse(user);
            Guid recipeId = Guid.Parse(recipe);
            var fb = new FeedBack();
            fb.own = userId;
            fb.recipe_id = recipeId;
            fb.content = content;
            fb.createAt = DateTime.Now;
            // if(ModelState.IsValid)
            db.feedBack.Add(fb);
            db.SaveChanges();

            return Json(new { success = true, responseText = "Success" }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult deleteComment(Guid id, Guid recipeId)
        {
            var com = db.feedBack.Find(id);
            if (com != null)
            {
                db.feedBack.Remove(com);
                db.SaveChanges();
            }
            return RedirectToAction("recipeDetail", new { id = recipeId });
        }
    }
}

eproject/Views/Contest/Index.cshtml
@model PagedList.IPagedList<eproject.Models.Contest>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/home.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="contest">
    <div class="container ">
        <div class="row">
            <div class="col-sm-12 wow flipInY">
                @using (Ajax.BeginForm("Index", "Contest", new AjaxOptions { InsertionMode = InsertionMode.Replace }, FormMethod.Get))
                {
                    <span>
                        <b>Find by contest name</b> @Html.TextBox("search", ViewBag.CurrentFilter as string)
                        <input type="submit" value="Search" class="btn btn-info" />
                    </span>
                }
                <br />
                <table class="table table-striped table-bordered table-sm text-justify" cellspacing="0">
                    <tr>
                        <th>
                            Contest Name
                            <a href="@Url.Action("Index","Contest", new { sortOrder = ViewBag.NameSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th>
                            Create Date
                            <a href="@Url.Action("Index","Contest", new { sortOrder = ViewBag.CreateDateSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th>
                            Start Date
                            <a href="@Url.Action("Index","Contest", new { sortOrder = ViewBag.StartDateSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th>
                            End Date
                            <a href="@Url.Action("Index","Contest", new { sortOrder = ViewBag.EndDateSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink(item.name, "contestRecipe", "Contest", new { id = item.id, endDate = item.endDate, winner = item.winner }, "")
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.createAt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.startDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.endDate)
                            </td>
                            <td>
                                @Html.ActionLink("Read More", "readmore", new { id = item.id }, new { @class = "btn btn-warning" })
                            </td>
                        </tr>
                    }
                </table>
                <br />
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("Index",
                    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>
        </div>
    </div>
</div>

eproject/Views/Contest/Readmore.cshtml
@model eproject.Models.Contest

@{
    ViewBag.Title = "Readmore";
    Layout = "~/Views/Shared/home.cshtml";
}
<div class="contest">
    <div class="container ">
        <div class="row">
            <div class="col-sm-12 wow flipInY">
                <div>

                    <hr />
                    <dl class="dl-horizontal">
                        <h3>@Html.DisplayFor(model => model.name)</h3>
                        <br />                      
                        <dd>
                            @Html.Raw(Model.content)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.startDate) - @Html.DisplayNameFor(model => model.endDate) : @Html.DisplayFor(model => model.startDate) - @Html.DisplayFor(model => model.endDate)
                        </dt>
                    </dl>
                </div>
                <p>
                    @if (Model.startDate <= DateTime.Today && Model.endDate > DateTime.Today)
                    {
                        @Html.ActionLink("Join", "Create", "Recipes", new { id = Model.id }, new { @class = "btn btn-success" })
                    }
                    else
                    {
                        @Html.ActionLink("Join", "Create", "Recipes", null, new { @class = "btn btn-success disabled" })
                    }
                    <br /><br />
                    @Html.ActionLink("Back to List", "Index")
                </p>
            </div>
        </div>
    </div>
</div>

eproject/Views/Contest/contestRecipe.cshtml
@model PagedList.IPagedList<eproject.Models.Recipe>
@using PagedList.Mvc;

@{
    ViewBag.Title = "contestRecipe";
    Layout = "~/Views/Shared/home.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<br />
<div class="contest">
    <div class="container ">
        <div class="row">
            <div class="col-sm-12 wow flipInY">
                <input type="hidden" id="contest_id" name="contest_id" value="@ViewBag.contestId" />
                <input type="hidden" id="end_date" name="end_date" value="@ViewBag.endDate" />
                <input type="hidden" id="winner" name="winner" value="@ViewBag.w" />
                @using (Ajax.BeginForm("contestRecipe", "Contest", new AjaxOptions { InsertionMode = InsertionMode.Replace }, FormMethod.Get))
                {
                    if (@ViewBag.endDate <= DateTime.Today && @ViewBag.winner != null)
                    {
                        <h3 style="color:red">
                            The winner is : @ViewBag.winner @Html.ActionLink("Detail", "recipeDetail", "RecipeExtend",
                            new { id = @ViewBag.w }, new { target = "_blank", @class = "btn btn-warning" })
                        </h3>
                    }
                    <br />
                    <span>
                        <b>Find by recipe name</b> @Html.TextBox("search", ViewBag.CurrentFilter as string)
                        <input type="submit" value="Search" class="btn btn-info" />
                    </span>
                }
                <br />
                <table class="table table-striped table-bordered table-sm text-justify" cellspacing="0" width="100%">
                    <tr>                       
                        <th>
                            Recipe Name
                            <a href="@Url.Action("contestRecipe","Contest", new { sortOrder = ViewBag.NameSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th>
                            Create Date
                            <a href="@Url.Action("contestRecipe","Contest", new { sortOrder = ViewBag.CreateDateSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th>
                            Category
                            <a href="@Url.Action("contestRecipe","Contest", new { sortOrder = ViewBag.StartDateSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>                         
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.createAt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.category)
                            </td>
                            <td>
                                @Html.ActionLink("Read More", "recipeDetail", "RecipeExtend", new { id = item.id }, new { @class = "btn btn-warning", target = "_blank" })
                            </td>
                        </tr>
                    }
                </table>
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
                <br />
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("contestRecipe",
                    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>
        </div>
    </div>
</div>