eproject/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace eproject.Models
{
    public class Recipe
    {
        public Recipe()
        {
            //this.role = "ROLE_USER";
            this.enabled = false;
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid id { get; set; }
        [MaxLength(30)]
        [Required(ErrorMessage = "name not blank!")]
        public string name { get; set; }
        [Required(ErrorMessage = "not blank!")]
        public string category { get; set; }
        [Required(ErrorMessage = "not blank!")]
        public string content { get; set; }
        [Required(ErrorMessage = "not blank")]
        public string type { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime createAt { get; set; }
        public bool enabled { get; set; }

        public string image { get; set; }

        [ForeignKey("User")]
        public Guid manager { get; set; }
        public virtual User User { get; set; }
        [NotMapped]
        public HttpPostedFileBase imgFile { get; set; }
        public virtual ICollection<FeedBack> FeedBacks { get; set; }

        [ForeignKey("Contest")]
        public Guid? contest_id { get; set; }
        public virtual Contest Contest { get; set; }

        [NotMapped]
        public double rate { get; set; }

        public int viewCount { get; set; } = 0;
    }
}

eproject/Controllers/AdminController.cs
using eproject.Models;
using eproject.Security;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace eproject.Controllers
{
    public class AdminController : Controller
    {
        private context db = new context();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult index([Bind(Include = "email,pass")] User ouser)
        {
            if (ouser.email == null || ouser.pass == null)
            {
                return View(ouser);
            }
            var user = db.user.Where(m => m.email == ouser.email).SingleOrDefault();
            if (user != null && pass.VerifyHashedPassword(user.pass, ouser.pass))
            {
                Session["userId"] = user.id;
                Session["email"] = user.email;
                return RedirectToAction("user", "admin");
            }
            ModelState.AddModelError("", "email or password error");
            return View(ouser);
        }
        //custom authorize
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult user(string search)
        {
            if (search != null && search != "")
            {
                return View(db.user.Where(c => c.role == "ROLE_USER" && (c.email.ToLower().Contains(search.ToLower()) || c.name.ToLower().Contains(search.ToLower()))));
            }
            return View(db.user.Where(c => c.role == "ROLE_USER"));
        }
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult edituser(Guid id, bool enabled)
        {
            var user = db.user.Find(id);
            user.enabled = enabled;
            db.SaveChanges();
            return RedirectToAction("user");
        }
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult recipe(string search)
        {
            if (search != null && search != "")
            {
                return View(db.recipe.Where(c => c.name.ToLower().Contains(search.ToLower()) || c.category.ToLower().Contains(search.ToLower())));
            }
            return View(db.recipe);
        }
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult editRecipe(Guid id, bool enabled)
        {
            var recipe = db.recipe.Find(id);
            recipe.enabled = enabled;
            db.SaveChanges();
            return RedirectToAction("recipe");
        }

        // GET: Contest/Sorting/Searching/Paging 
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult contestIndex(string sortOrder, string currentFilter, string search, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.CreateDateSort = sortOrder == "datecreate" ? "createdate" : "datecreate";
            ViewBag.StartDateSort = sortOrder == "datestart" ? "stardate" : "datestart";
            ViewBag.EndDateSort = sortOrder == "dateend" ? "enddate" : "dateend";

            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewBag.CurrentFilter = search;

            var contests = from c in db.contest
                           select c;

            // Searching
            if (!String.IsNullOrEmpty(search))
            {
                contests = contests.Where(c => c.name.Contains(search));
            }

            //Sorting
            switch (sortOrder)
            {
                case "datecreate":
                    contests = contests.OrderBy(c => c.createAt);
                    break;
                case "name":
                    contests = contests.OrderBy(c => c.name);
                    break;
                case "":
                    contests = contests.OrderByDescending(c => c.name);
                    break;
                case "datestart":
                    contests = contests.OrderBy(c => c.startDate);
                    break;
                case "stardate":
                    contests = contests.OrderByDescending(c => c.startDate);
                    break;
                case "dateend":
                    contests = contests.OrderBy(c => c.endDate);
                    break;
                case "enddate":
                    contests = contests.OrderByDescending(c => c.endDate);
                    break;
                default:
                    contests = contests.OrderByDescending(c => c.createAt);
                    break;
            }

            //Paging
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(contests.ToPagedList(pageNumber, pageSize));
        }

        // GET: Contest/Create
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult contestCreate()
        {
            return View();
        }

        // POST: Contest/Create
        [AuthorizeUser(role = "ROLE_ADMIN")]
        [HttpPost]
        public ActionResult contestCreate(Contest newcontest)
        {
            //Check contest name exist
            if (db.contest.Any(x => x.name == newcontest.name))
            {
                ModelState.AddModelError("name", "Contest name already exist");
                return View(newcontest);
            }
            //Check start date
            if (newcontest.startDate < DateTime.Today)
            {
                ModelState.AddModelError("startDate", "Start date cannot be less than current date");
                return View(newcontest);
            }
            //Check end date
            if (newcontest.endDate <= newcontest.startDate)
            {
                ModelState.AddModelError("endDate", "End date cannot be equal or less than start date");
                return View(newcontest);
            }
            if (ModelState.IsValid)
            {
                db.contest.Add(newcontest);
                newcontest.createAt = DateTime.Today;
                db.SaveChanges();
                return RedirectToAction("contestIndex", "admin");
            }
            return View(newcontest);
        }


        // GET: Contest/Details
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult contestDetails(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.contest.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // GET: Contest/Edit
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult contestEdit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.contest.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // POST: Contest/Edit
        [AuthorizeUser(role = "ROLE_ADMIN")]
        [HttpPost]
        public ActionResult contestEdit([Bind(Include = "id,name,content,createAt,startDate,endDate")] Contest editcontest)
        {
            //Check contest name exist          
            if (db.contest.Any(x => x.name == editcontest.name && x.id != editcontest.id))
            {
                ModelState.AddModelError("name", "Contest name already exist");
                return View(editcontest);
            }
            //Check start date
            if (editcontest.startDate < editcontest.createAt)
            {
                ModelState.AddModelError("startDate", "Start date cannot be less than create date");
                return View(editcontest);
            }
            //Check end date
            if (editcontest.endDate <= editcontest.startDate)
            {
                ModelState.AddModelError("endDate", "End date cannot be equal or less than start date");
                return View(editcontest);
            }
            if (ModelState.IsValid)
            {
                db.Entry(editcontest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("contestIndex", "admin");
            }
            return View(editcontest);
        }

        // GET: Contests/Delete
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult contestDelete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contest contest = db.contest.Find(id);
            if (contest == null)
            {
                return HttpNotFound();
            }
            return View(contest);
        }

        // POST: Contests/Delete
        [AuthorizeUser(role = "ROLE_ADMIN")]
        [HttpPost, ActionName("contestDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult contestDeleteConfirmed(Guid id)
        {
            Contest contest = db.contest.Find(id);
            db.contest.Remove(contest);
            db.SaveChanges();
            return RedirectToAction("contestIndex", "admin");
        }

        // GET: ContestRecipe/Sorting/Searching/Paging 
        [AuthorizeUser(role = "ROLE_ADMIN")]
        public ActionResult contestRecipe(string sortOrder, string currentFilter, string search, int? page, Guid? id, DateTime? endDate, Guid? winner)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.CreateDateSort = sortOrder == "datecreate" ? "createdate" : "datecreate";

eproject/Controllers/RecipeExtendController.cs
using eproject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eproject.Helper;
using eproject.Security;

namespace eproject.Controllers
{
    public class RecipeExtendController : Controller
    {
        private context db = new context();
        // GET: RecipeExtend
        [HttpPost]

        public ActionResult rate(int ratting, string user, string recipe)
        {
            if (recipe == "" || user == "")
            {
                return Json(new { success = false, responseText = "you must log in before ratting!" }, JsonRequestBehavior.AllowGet);
            }
            Guid userId = Guid.Parse(user);
            Guid recipeId = Guid.Parse(recipe);
            var orate = db.ratting.Where(c => c.recipe_id == recipeId && c.own == userId);

            if (orate.Count() != 0)
            {
                return Json(new { success = false, responseText = "You already rate this recipe!" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Ratting nrate = new Ratting();
                nrate.rate = ratting;
                nrate.own = userId;
                nrate.recipe_id = recipeId;
                db.ratting.Add(nrate);
                db.SaveChanges();
                return Json(new { success = true, responseText = "You have rate this recipe " + ratting + " star!" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult recipeDetail(Guid id)
        {
            double rate = 0;
            int rateCount = 0;
            var recipe = db.recipe.Find(id);
            if (recipe.enabled == false)
            {
                return RedirectToAction("index", "home");
            }
            var type = recipe.type;
            if (type != "Free")
            {
                if (Session["userId"] != null)
                {
                    var u = db.user.Find(Session["userId"]);
                    if (u.expireDate < DateTime.Now && u.role != "ROLE_ADMIN")
                    {
                        return RedirectToAction("error", "home", new { msg = "Only vip user can see this recipe, go to profile to buy vip access!" });
                    }
                }
                else
                    return RedirectToAction("error", "home", new { msg = "Only vip user can see this recipe, go to profile to buy vip access!" });

            }
            ViewBag.manager = db.user.Find(recipe.manager).email;
            var srate = db.ratting.Where(m => m.recipe_id == recipe.id).Select(m => m.rate);
            if (srate.Count() > 0)
            {
                rate = srate.Average();
                rateCount = srate.Count();
            }
            //random 3 recipe with same category
            var relate = db.recipe.Where(m => m.category == recipe.category).OrderBy(x => Guid.NewGuid()).Take(3);

            var comment = db.feedBack.Where(m => m.recipe_id == recipe.id).ToArray();

            foreach (var item in comment)
            {
                item.ago = DateTimeConvert.TimeAgo(item.createAt);
                item.name = db.user.Find(item.own).name;

            }
            ViewBag.comment = comment;
            ViewBag.rateCount = rateCount;
            ViewBag.rate = rate;
            ViewBag.recipeId = id;
            ViewBag.relate = relate;
            //view count
            if (Request.Cookies["ViewedPage"] != null)
            {
                if (Request.Cookies["ViewedPage"][string.Format("pId_{0}", id)] == null)
                {
                    HttpCookie cookie = (HttpCookie)Request.Cookies["ViewedPage"];
                    cookie[string.Format("pId_{0}", id)] = "1";
                    cookie.Expires = DateTime.Now.AddDays(1);
                    Response.Cookies.Add(cookie);
                    recipe.viewCount = recipe.viewCount + 1;
                    db.SaveChanges();
                }
            }
            else
            {
                HttpCookie cookie = new HttpCookie("ViewedPage");
                cookie[string.Format("pId_{0}", id)] = "1";
                cookie.Expires = DateTime.Now.AddDays(1);
                Response.Cookies.Add(cookie);

                recipe.viewCount = recipe.viewCount + 1;
                db.SaveChanges();
            }
            return View(recipe);
        }
        [HttpPost]
        public ActionResult createComment(string content, string user, string recipe)
        {
            if (recipe == "" || user == "")
            {
                return Json(new { success = false, responseText = "you must log in before ratting!" }, JsonRequestBehavior.AllowGet);
            }
            if (content.Length < 20 || content.Length > 150)
            {
                return Json(new { success = false, responseText = "comment must at 20-150 character" }, JsonRequestBehavior.AllowGet);
            }
            Guid userId = Guid.Parse(user);
            Guid recipeId = Guid.Parse(recipe);
            var fb = new FeedBack();
            fb.own = userId;
            fb.recipe_id = recipeId;
            fb.content = content;
            fb.createAt = DateTime.Now;
            // if(ModelState.IsValid)
            db.feedBack.Add(fb);
            db.SaveChanges();

            return Json(new { success = true, responseText = "Success" }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult deleteComment(Guid id, Guid recipeId)
        {
            var com = db.feedBack.Find(id);
            if (com != null)
            {
                db.feedBack.Remove(com);
                db.SaveChanges();
            }
            return RedirectToAction("recipeDetail", new { id = recipeId });
        }
    }
}

eproject/Views/Admin/contestCreate.cshtml
@model eproject.Models.Contest
@{
    ViewBag.Title = "Create contest";
    Layout = "~/Views/Shared/admin.cshtml";
}
<h2>Create Contest</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <b>@Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })               
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>@Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md">
                @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>@Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md">
                @Html.EditorFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <b>@Html.LabelFor(model => model.content, htmlAttributes: new { @class = "control-label col-md-2" })</b>
            <div class="col-md">
                @Html.TextAreaFor(model => model.content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" style="margin-left:560px" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "contestIndex")
</div>

<script src="~/Scripts/tinymce/tinymce.js"></script>
<script>tinymce.init({ selector: '#content' });</script>

eproject/Views/Admin/contestDelete.cshtml
@model eproject.Models.Contest
@{
    ViewBag.Title = "contestDelete";
    Layout = "~/Views/Shared/Admin.cshtml";
}

<h2>Delete Contest</h2>
<div>
    <hr />
    <h4>Are you sure you want to delete @Html.DisplayFor(model => model.name) ?</h4>
    <br />
    <div class="contest">
        <dl class="dl-horizontal">
            <dd>
                @Html.Raw(Model.content)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.createAt) : @Html.DisplayFor(model => model.createAt)
            </dt>
            <dt>
                @Html.DisplayNameFor(model => model.startDate) - @Html.DisplayNameFor(model => model.endDate) :
                @Html.DisplayFor(model => model.startDate) -  @Html.DisplayFor(model => model.endDate)
            </dt>
        </dl>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" style="margin-left:560px"/>
        </div>
    }
    <br />
    <div>
        @Html.ActionLink("Back to List", "contestIndex")
    </div>
</div>

eproject/Views/Admin/contestIndex.cshtml
@model PagedList.IPagedList<eproject.Models.Contest>
@using PagedList.Mvc;

@{
    ViewBag.Title = "contestIndex";
    Layout = "~/Views/Shared/admin.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="createcontest">
    @Html.ActionLink("Create New", "contestCreate", null, new { @class = "btn btn-primary" })
</div>

<br /><br />
      <div class="contest">
          <div class="container ">
              <div class="row">
                  <div class="col-sm-12 wow flipInY">
                      @using (Ajax.BeginForm("contestIndex", "Admin", new AjaxOptions { InsertionMode = InsertionMode.Replace }, FormMethod.Get))
                      {
                          <span>
                              <b>Find by contest name</b> @Html.TextBox("search", ViewBag.CurrentFilter as string)
                              <input type="submit" value="Search" class="btn btn-info" />
                          </span>
                      }
                      <br />
                      <table class="table table-striped table-bordered table-sm text-justify" cellspacing="0">
                          <tr>
                              <th>
                                  Contest Name
                                  <a href="@Url.Action("contestIndex","Admin", new { sortOrder = ViewBag.NameSort })">
                                      <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                                  </a>
                              </th>
                              <th>
                                  Create Date
                                  <a href="@Url.Action("contestIndex","Admin", new { sortOrder = ViewBag.CreateDateSort })">
                                      <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                                  </a>
                              </th>
                              <th>
                                  Start Date
                                  <a href="@Url.Action("contestIndex","Admin", new { sortOrder = ViewBag.StartDateSort })">
                                      <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                                  </a>
                              </th>
                              <th>
                                  End Date
                                  <a href="@Url.Action("contestIndex","Admin", new { sortOrder = ViewBag.EndDateSort })">
                                      <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                                  </a>
                              </th>
                              <th></th>
                          </tr>

                          @foreach (var item in Model)
                          {
                              <tr>
                                  <td>
                                      @Html.ActionLink(item.name, "contestRecipe", "Admin", new { id = item.id , endDate = item.endDate, winner = item.winner }, "")
                                  </td>
                                  <td>
                                      @Html.DisplayFor(modelItem => item.createAt)
                                  </td>
                                  <td>
                                      @Html.DisplayFor(modelItem => item.startDate)
                                  </td>
                                  <td>
                                      @Html.DisplayFor(modelItem => item.endDate)
                                  </td>
                                  <td>
                                      @Html.ActionLink("Edit", "contestEdit", new { id = item.id }, new { @class = "btn btn-success" })
                                      @Html.ActionLink("Details", "contestDetails", new { id = item.id }, new { @class = "btn btn-warning" })
                                      @Html.ActionLink("Delete", "contestDelete", new { id = item.id }, new { @class = "btn btn-danger" })
                                  </td>
                              </tr>
                          }
                      </table>
                      <br />
                      Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                      @Html.PagedListPager(Model, page => Url.Action("contestIndex",
                          new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                  </div>
              </div>
          </div>
      </div>

eproject/Views/Admin/contestRecipe.cshtml
@model PagedList.IPagedList<eproject.Models.Recipe>
@using PagedList.Mvc;

@{
    ViewBag.Title = "contestRecipe";
    Layout = "~/Views/Shared/Admin.cshtml";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<br />
<div class="contest">
    <div class="container ">
        <div class="row">
            <div class="col-sm-12 wow flipInY">
                <input type="hidden" id="contest_id" name="contest_id" value="@ViewBag.contestId" />
                <input type="hidden" id="end_date" name="end_date" value="@ViewBag.endDate" />
                <input type="hidden" id="winner" name="winner" value="@ViewBag.winner" />               

                @using (Ajax.BeginForm("contestRecipe", "Admin", new AjaxOptions { InsertionMode = InsertionMode.Replace }, FormMethod.Get))
                {
                    if (@ViewBag.endDate <= DateTime.Today && @ViewBag.winner == null)
                    {
                        <h3 style="color:red">Please choose one a winner</h3>
                    }
                    <hr /><br />
                    if (@ViewBag.endDate <= DateTime.Today && @ViewBag.winner != null)
                    {
                          <h3 style="color:red">The winner is: @ViewBag.winner @Html.ActionLink("Detail", "recipeDetail", "RecipeExtend", 
                                                                            new { id = @ViewBag.winner }, new { target = "_blank", @class = "btn btn-warning" })</h3>                      
                    }
                    <br />
                    <span>
                        <b>Find by recipe name</b> @Html.TextBox("search", ViewBag.CurrentFilter as string)
                        <input type="submit" value="Search" class="btn btn-info" />
                    </span>
                }
                <br />
                <table class="table table-striped table-bordered table-sm text-justify" cellspacing="0" width="100%">
                    <tr>
                        <th>
                            RecipeID
                        </th>
                        <th>
                            Recipe Name
                            <a href="@Url.Action("contestRecipe","Admin", new { sortOrder = ViewBag.NameSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th>
                            Create Date
                            <a href="@Url.Action("contestRecipe","Admin", new { sortOrder = ViewBag.CreateDateSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        <th>
                            Category
                            <a href="@Url.Action("contestRecipe","Admin", new { sortOrder = ViewBag.StartDateSort })">
                                <img src="~/images/updown.svg" alt="Alternate Text" style="width: 15px;" />
                            </a>
                        </th>
                        @if (@ViewBag.endDate <= DateTime.Today && @ViewBag.winner == null)
                        {
                            <th>
                                Choose a Winner
                            </th>
                        }
                        else
                        {
                            <th>
                                Winner
                            </th>
                        }
                    </tr>

                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.id)
                        </td>
                        <td>
                            @Html.ActionLink(item.name, "recipeDetail", "RecipeExtend", new { id = item.id }, new { target = "_blank" })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.createAt)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.category)
                        </td>
                        @if (@ViewBag.endDate <= DateTime.Today && @ViewBag.winner == null)
                        {
                            <td>                                
                                @Html.ActionLink("Winner", "setWinner", "Admin",
                               new { id = item.contest_id, winner = item.id, enddate = @ViewBag.enddate}, new { @class = "btn btn-danger" })                                
                            </td>
                        }
                        else
                        {
                            <td>
                                @Html.ActionLink("Winner", "setWinner", "Admin",
                               null, new { @class = "btn btn-danger disabled" })
                            </td>
                        }
                    </tr>
                    }
                </table>
                <div>
                    @Html.ActionLink("Back to List", "contestIndex")
                </div>
                <br />
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("contestRecipe",
                    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>
        </div>
    </div>
</div>